name: refbrain-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23
  - pandas>=1.5
  - scipy>=1.9
  - matplotlib>=3.5
  - seaborn>=0.12
  - scikit-image>=0.19
  - tifffile
  - imagecodecs
  - pyvista>=0.46
  - vtk>=9.0
  - imagecodecs
  - notebook
  - ipython
  - pip
  - pip:
    - tqdm>=4.64
